-- достает статьи с авторами, но в виде
-- статья1 автор1
-- статья1 автор2

SELECT s.KEY_ID,aa.POS ,aa.KEY_ID , aa.NAME_LONG, s.JTITLE_, s.DOI_, s.N_AUTHOR, s.YEAR_ FROM ARTICLE_AUTHOR aa
RIGHT JOIN
(SELECT a.KEY_ID, a.DOI_, a.N_AUTHOR,a.JTITLE_, a.YEAR_  FROM ARTICLE a WHERE a.JOURNAL_ID in( 
SELECT JOURNAL_ID FROM JOURNAL2FIELD2CATEGORY 
WHERE FIELD_ID =(SELECT KEY_ID  FROM SCALAR s  WHERE TYPE_KEY_ID =3 AND NAME ='BIOPHYSICS'))) s
ON aa.ARTICLE_ID =s.KEY_ID

